server:
  tomcat:
    keep-alive-timeout: -1
    connection-timeout: 999999999
  port: 8070

spring:
  sleuth:
    enabled: true
  #  output:
  #    ansi:
  #      enabled: always
  datasource:
    url: jdbc-path
    username: dummyuser
    password: dummypass
    driver-class-name: @driver-class-name@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type: INFO
  #  config:
  #    use-legacy-processing: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
  file:
    name: logs/dev_app.log
